//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles SpaceGroupUpdatedEvent: triggered when a spacegroup is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.EventHandlers;

    public class SpaceGroupUpdatedEventHandler : INotificationHandler<SpaceGroupUpdatedEvent>
    {
        private readonly ILogger<SpaceGroupUpdatedEventHandler> _logger;

        public SpaceGroupUpdatedEventHandler(
            ILogger<SpaceGroupUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(SpaceGroupUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
