//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles SpaceGroupDeletedEvent: triggered when a spacegroup is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.EventHandlers;

    public class SpaceGroupDeletedEventHandler : INotificationHandler<SpaceGroupDeletedEvent>
    {
        private readonly ILogger<SpaceGroupDeletedEventHandler> _logger;

        public SpaceGroupDeletedEventHandler(
            ILogger<SpaceGroupDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(SpaceGroupDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
