//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for UpdateChargeCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a charge.
// Docs: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.Update;

public class UpdateChargeCommandValidator : AbstractValidator<UpdateChargeCommand>
{
        public UpdateChargeCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.EffectiveDate).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

          
        }
    
}

