//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for creating a new Member.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/member
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Members.Commands.Create;

public class CreateMemberCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("License plate")]
    public string? LicensePlate { get; set; }
    [Description("Card id")]
    public string? CardId { get; set; }
    [Description("Start date")]
    public DateTime? StartDate { get; set; }
    [Description("Expiry date")]
    public DateTime? ExpiryDate { get; set; }
    [Description("Space group id")]
    public int? SpaceGroupId { get; set; }
    [Description("Space group")]
    public SpaceGroupDto? SpaceGroup { get; set; }
    [Description("Space type")]
    public SpaceTypes? SpaceType { get; set; }
    [Description("Space no")]
    public string? SpaceNo { get; set; }
    [Description("Is active")]
    public bool IsActive { get; set; }
    [Description("Name")]
    public string Name { get; set; }
    [Description("Phone number")]
    public string? PhoneNumber { get; set; }
    [Description("Mobile number")]
    public string? MobileNumber { get; set; }
    [Description("Email")]
    public string? Email { get; set; }
    [Description("Address")]
    public string? Address { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }
    [Description("Tenant id")]
    public string? TenantId { get; set; }
    [Description("Tenant")]
    public TenantDto? Tenant { get; set; }
    [Description("Member rentals")]
    public List<MemberRentalDto>? MemberRentals { get; set; }
    [Description("Member Vehicles")]
    public List<MemberVehicleDto>? MemberVehicles { get; set; }
    public string CacheKey => MemberCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => MemberCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateMemberCommand, Member>(MemberList.None)
                .ForMember(x=>x.SpaceGroup,y=>y.Ignore())
                .ForMember(x => x.MemberRentals, y => y.Ignore())
                .ForMember(x => x.Tenant, y => y.Ignore());
        }
    }
}

public class CreateMemberCommandHandler : IRequestHandler<CreateMemberCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public CreateMemberCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(CreateMemberCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<Member>(request);
        item.SpaceGroupId = request.SpaceGroup?.Id;
        item.MemberRentals=new List<MemberRental>();
        foreach (var ren in request.MemberRentals??  Enumerable.Empty<MemberRentalDto>())
        {
            var renEntity = _mapper.Map<MemberRental>(ren);
            item.MemberRentals.Add(renEntity);
        }
        // raise a create domain event
        item.AddDomainEvent(new MemberCreatedEvent(item));
        db.Members.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(item.Id);
    }
}

