//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a car wash by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same car wash.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CarWashes.Caching;
using CleanArchitecture.Blazor.Application.Features.CarWashes.DTOs;
using CleanArchitecture.Blazor.Application.Features.CarWashes.Specifications;
using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Entities;

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Queries.GetById;

public class GetCarWashByIdQuery : ICacheableRequest<Result<CarWashDto>>
{
   public required int Id { get; set; }
   public string CacheKey => CarWashCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => CarWashCacheKey.Tags;
}

public class GetCarWashByIdQueryHandler :
     IRequestHandler<GetCarWashByIdQuery, Result<CarWashDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetCarWashByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<CarWashDto>> Handle(GetCarWashByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.CarWashes.ApplySpecification(new CarWashByIdSpecification(request.Id))
                                                .ProjectTo<CarWashDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Lavado con id: [{request.Id}] no encontrado.");

        var additionals = await db.CarWashAdditionals.Where(x => x.CarWashId == request.Id)
            .ProjectTo<CarWashAdditionalDto>(_mapper.ConfigurationProvider).ToListAsync(cancellationToken);
        data.Additionals = additionals;

        var operators = await db.CarWashOperators.Where(x => x.CarWashId == request.Id)
            .ProjectTo<CarWashOperatorDto>(_mapper.ConfigurationProvider).ToListAsync(cancellationToken);
        data.Operators = operators;

        var member = data.MemberId.HasValue
            ? await db.Members.Where(m => m.Id == data.MemberId.Value)
                .ProjectTo<MemberDto>(_mapper.ConfigurationProvider).FirstOrDefaultAsync(cancellationToken)
            : null;
        data.Member = member;

        return await Result<CarWashDto>.SuccessAsync(data);
    }
}
