//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       Charge entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Charges.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of Charges.
/// </summary>
public class ChargeAdvancedSpecification : Specification<Charge>
{
    public ChargeAdvancedSpecification(ChargeAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(ChargeListView.TODAY.ToString(), filter.CurrentUser.LocalTimeOffset);
        var last30daysrange = today.GetDateRange(ChargeListView.LAST_30_DAYS.ToString(),filter.CurrentUser.LocalTimeOffset);

        Query.Where(q => q.Name != null)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedById == filter.CurrentUser.UserId, filter.ListView == ChargeListView.My && filter.CurrentUser is not null)
             .Where(x => x.CreatedAt >= todayrange.Start && x.CreatedAt < todayrange.End.AddDays(1), filter.ListView == ChargeListView.TODAY)
             .Where(x => x.CreatedAt >= last30daysrange.Start, filter.ListView == ChargeListView.LAST_30_DAYS);
       
    }
}
