//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for CreateHolidayCommand: enforces max lengths and required fields for Holiday entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Create;

public class CreateHolidayCommandValidator : AbstractValidator<CreateHolidayCommand>
{
        public CreateHolidayCommandValidator()
        {
                RuleFor(v => v.Date).NotNull(); 
    RuleFor(v => v.Name_En).MaximumLength(255); 
    RuleFor(v => v.Name_Tc).MaximumLength(255); 

        }
       
}

