//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for AddEditMemberCommand: enforces field length and required property rules for Member entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/member
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Members.Commands.AddEdit;

public class AddEditMemberCommandValidator : AbstractValidator<AddEditMemberCommand>
{
    public AddEditMemberCommandValidator()
    {
                RuleFor(v => v.LicensePlate).MaximumLength(255); 
    RuleFor(v => v.CardId).MaximumLength(255); 
    RuleFor(v => v.StartDate).NotNull(); 
    RuleFor(v => v.ExpiryDate).NotNull(); 
    RuleFor(v => v.SpaceType).NotNull(); 
    RuleFor(v => v.SpaceNo).MaximumLength(255); 
    RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.PhoneNumber).MaximumLength(255); 
    RuleFor(v => v.MobileNumber).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.Address).MaximumLength(255); 
    RuleFor(v => v.Notes).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

     }

}

