//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles CarparkDeletedEvent: triggered when a carpark is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Carparks.EventHandlers;

    public class CarparkDeletedEventHandler : INotificationHandler<CarparkDeletedEvent>
    {
        private readonly ILogger<CarparkDeletedEventHandler> _logger;

        public CarparkDeletedEventHandler(
            ILogger<CarparkDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CarparkDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
