//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Defines permission constants for gate operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Gate Permissions")]
    [Description("Set permissions for gate operations.")]
    public static class Gates
    {
        [Description("Allows viewing gate details.")]
        public const string View = "Permissions.Gates.View";
        [Description("Allows creating gate records.")]
        public const string Create = "Permissions.Gates.Create";
        [Description("Allows cloning existing gate records.")]
        public const string Clone = "Permissions.Gates.Clone";
        [Description("Allows modifying existing gate details.")]
        public const string Edit = "Permissions.Gates.Edit";
        [Description("Allows deleting gate records.")]
        public const string Delete = "Permissions.Gates.Delete";
        [Description("Allows printing gate details.")]
        public const string Print = "Permissions.Gates.Print";
        [Description("Allows searching gate records.")]
        public const string Search = "Permissions.Gates.Search";
        [Description("Allows exporting gate records.")]
        public const string Export = "Permissions.Gates.Export";
        [Description("Allows importing gate records.")]
        public const string Import = "Permissions.Gates.Import";
    }
}

public class GatesAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Clone { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
