//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for UpdateZoneCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a zone.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Update;

public class UpdateZoneCommandValidator : AbstractValidator<UpdateZoneCommand>
{
        public UpdateZoneCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.CarparkId).NotNull(); 
    RuleFor(v => v.HolidaySets).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Identifier).MaximumLength(255); 

          
        }
    
}

