//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for UpdateCarparkCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a carpark.
// Docs: https://docs.cleanarchitectureblazor.com/features/carpark
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Commands.Update;

public class UpdateCarparkCommandValidator : AbstractValidator<UpdateCarparkCommand>
{
        public UpdateCarparkCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.AppKey).MaximumLength(255); 
    RuleFor(v => v.MachineCode).MaximumLength(255); 
    RuleFor(v => v.RegistrationCode).MaximumLength(255); 
    RuleFor(v => v.ContactPerson).MaximumLength(255); 
    RuleFor(v => v.PhoneNumber).MaximumLength(255); 
    RuleFor(v => v.Fax).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Identified).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

          
        }
    
}

