//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a charge by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same charge.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Charges.DTOs;
using CleanArchitecture.Blazor.Application.Features.Charges.Caching;
using CleanArchitecture.Blazor.Application.Features.Charges.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Charges.Queries.GetById;

public class GetChargeByIdQuery : ICacheableRequest<Result<ChargeDto>>
{
   public required int Id { get; set; }
   public string CacheKey => ChargeCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => ChargeCacheKey.Tags;
}

public class GetChargeByIdQueryHandler :
     IRequestHandler<GetChargeByIdQuery, Result<ChargeDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetChargeByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<ChargeDto>> Handle(GetChargeByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Charges.ApplySpecification(new ChargeByIdSpecification(request.Id))
                                                .ProjectTo<ChargeDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Charge with id: [{request.Id}] not found.");
        return await Result<ChargeDto>.SuccessAsync(data);
    }
}
