//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for deleting Member entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/member
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Members.Commands.Delete;

public class DeleteMemberCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => MemberCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => MemberCacheKey.Tags;
  public DeleteMemberCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteMemberCommandHandler : 
             IRequestHandler<DeleteMemberCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteMemberCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteMemberCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Members.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new MemberDeletedEvent(item));
            db.Members.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

