//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for AddEditMemberRentalCommand: enforces field length and required property rules for MemberRental entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.AddEdit;

public class AddEditMemberRentalCommandValidator : AbstractValidator<AddEditMemberRentalCommand>
{
    public AddEditMemberRentalCommandValidator()
    {
                RuleFor(v => v.LicensePlate).MaximumLength(255); 
    RuleFor(v => v.CardId).MaximumLength(255); 
    RuleFor(v => v.RentalFee).NotNull(); 
    RuleFor(v => v.Deposit).NotNull(); 
    RuleFor(v => v.AmountDue).NotNull(); 
    RuleFor(v => v.AmountPaid).NotNull(); 
    RuleFor(v => v.PaymentTime).NotNull(); 
    RuleFor(v => v.PaymentMethodId).NotNull(); 
    RuleFor(v => v.Notes).MaximumLength(255); 

     }

}

