//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Defines permission constants for memberrental operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("MemberRental Permissions")]
    [Description("Set permissions for memberrental operations.")]
    public static class MemberRentals
    {
        [Description("Allows viewing memberrental details.")]
        public const string View = "Permissions.MemberRentals.View";
        [Description("Allows creating memberrental records.")]
        public const string Create = "Permissions.MemberRentals.Create";
        [Description("Allows cloning existing memberrental records.")]
        public const string Clone = "Permissions.MemberRentals.Clone";
        [Description("Allows modifying existing memberrental details.")]
        public const string Edit = "Permissions.MemberRentals.Edit";
        [Description("Allows deleting memberrental records.")]
        public const string Delete = "Permissions.MemberRentals.Delete";
        [Description("Allows printing memberrental details.")]
        public const string Print = "Permissions.MemberRentals.Print";
        [Description("Allows searching memberrental records.")]
        public const string Search = "Permissions.MemberRentals.Search";
        [Description("Allows exporting memberrental records.")]
        public const string Export = "Permissions.MemberRentals.Export";
        [Description("Allows importing memberrental records.")]
        public const string Import = "Permissions.MemberRentals.Import";
    }
}

public class MemberRentalsAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Clone { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
