//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a holiday by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same holiday.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Holidays.DTOs;
using CleanArchitecture.Blazor.Application.Features.Holidays.Caching;
using CleanArchitecture.Blazor.Application.Features.Holidays.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Queries.GetById;

public class GetHolidayByIdQuery : ICacheableRequest<Result<HolidayDto>>
{
   public required int Id { get; set; }
   public string CacheKey => HolidayCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => HolidayCacheKey.Tags;
}

public class GetHolidayByIdQueryHandler :
     IRequestHandler<GetHolidayByIdQuery, Result<HolidayDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetHolidayByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<HolidayDto>> Handle(GetHolidayByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Holidays.ApplySpecification(new HolidayByIdSpecification(request.Id))
                                                .ProjectTo<HolidayDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Holiday with id: [{request.Id}] not found.");
        return await Result<HolidayDto>.SuccessAsync(data);
    }
}
