version: '3.8'

services:
  aceparking:
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UseInMemoryDatabase=${USE_IN_MEMORY_DATABASE}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
      - AppConfigurationSettings__ApplicationUrl=${APP_URL}
      - AppConfigurationSettings__AppName=${APP_NAME}
      - AppConfigurationSettings__Company=${APP_COMPANY}
      - DatabaseSettings__DBProvider=${DB_PROVIDER}
      - DatabaseSettings__ConnectionString=${DB_CONNECTION_STRING}
      - AI__GeminiApiKey=${GEMINI_API_KEY}
      - SmtpClientOptions__UserName=${SMTP_USERNAME}
      - SmtpClientOptions__Port=${SMTP_PORT}
      - SmtpClientOptions__Host=${SMTP_HOST}
      - SmtpClientOptions__Password=${SMTP_PASSWORD}
      - SmtpClientOptions__DefaultFromEmail=${SMTP_DEFAULT_FROM}
      - Authentication__Microsoft__ClientId=${MS_CLIENT_ID}
      - Authentication__Microsoft__ClientSecret=${MS_CLIENT_SECRET}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}

 
    ports:
      - "5095:80"
      - "5096:443"
    restart: on-failure

  

volumes:
  mssql_data:

