//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       CarWash entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of CarWashes.
/// </summary>
public class CarWashAdvancedSpecification : Specification<CarWash>
{
    public CarWashAdvancedSpecification(CarWashAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(CarWashListView.TODAY.ToString(), filter.CurrentUser.LocalTimeOffset);
        var last30daysrange = today.GetDateRange(CarWashListView.LAST_30_DAYS.ToString(),filter.CurrentUser.LocalTimeOffset);

        Query.Where(q => q.LicensePlate != null)
             .Where(q => q.Status == filter.Status, filter.Status.HasValue)
             .Where(q => q.WashServiceType == filter.WashServiceType, filter.WashServiceType.HasValue)
             .Where(q => q.IsPaid == filter.IsPaid, filter.IsPaid.HasValue)
             .Where(q => q.ChargeToMonthly == filter.ChargeToMonthly, filter.ChargeToMonthly.HasValue)
             .Where(q=>q.LicensePlate.Contains(filter.LicensePlate), !string.IsNullOrEmpty(filter.LicensePlate))
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedById == filter.CurrentUser.UserId, filter.ListView == CarWashListView.My && filter.CurrentUser is not null)
             .Where(x => x.CreatedAt >= todayrange.Start && x.CreatedAt < todayrange.End.AddDays(1), filter.ListView == CarWashListView.TODAY)
             .Where(x => x.CreatedAt >= last30daysrange.Start, filter.ListView == CarWashListView.LAST_30_DAYS);
       
    }
}
