//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       MemberRental entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of MemberRentals.
/// </summary>
public class MemberRentalAdvancedSpecification : Specification<MemberRental>
{
    public MemberRentalAdvancedSpecification(MemberRentalAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(MemberRentalListView.TODAY.ToString(), filter.CurrentUser.LocalTimeOffset);
        var last30daysrange = today.GetDateRange(MemberRentalListView.LAST_30_DAYS.ToString(),filter.CurrentUser.LocalTimeOffset);

        Query.Where(q => q.MemberId != null)
                .Where(q=>q.CardId.Contains(filter.CardId), !string.IsNullOrEmpty(filter.CardId))
                .Where(q=>q.LicensePlate.Contains(filter.LicensePlate), !string.IsNullOrEmpty(filter.LicensePlate))
                .Where(q=>q.PaymentTime>= filter.PaymentFrom && q.PaymentTime<=filter.PaymentTo, filter.PaymentFrom.HasValue && filter.PaymentTo.HasValue)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedById == filter.CurrentUser.UserId, filter.ListView == MemberRentalListView.My && filter.CurrentUser is not null)
             .Where(x => x.CreatedAt >= todayrange.Start && x.CreatedAt < todayrange.End.AddDays(1), filter.ListView == MemberRentalListView.TODAY)
             .Where(x => x.CreatedAt >= last30daysrange.Start, filter.ListView == MemberRentalListView.LAST_30_DAYS);
       
    }
}
