//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a specification for filtering a MemberRental entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering MemberRentals by their ID.
/// </summary>
public class MemberRentalByIdSpecification : Specification<MemberRental>
{
    public MemberRentalByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}