//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for DeleteVehicleCommand: ensures the ID list for vehicle is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.Delete;

public class DeleteVehicleCommandValidator : AbstractValidator<DeleteVehicleCommand>
{
        public DeleteVehicleCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

