//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for creating a new SpaceGroup.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/spacegroup
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.SpaceGroups.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Commands.Create;

public class CreateSpaceGroupCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Capacity")]
    public int Capacity {get;set;} 
    [Description("Zone id")]
    public int? ZoneId {get;set;} 
    [Description("Zone")]
    public ZoneDto? Zone {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 

      public string CacheKey => SpaceGroupCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => SpaceGroupCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateSpaceGroupCommand, SpaceGroup>(MemberList.None);
        }
    }
}
    
    public class CreateSpaceGroupCommandHandler : IRequestHandler<CreateSpaceGroupCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateSpaceGroupCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateSpaceGroupCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<SpaceGroup>(request);
           // raise a create domain event
	       item.AddDomainEvent(new SpaceGroupCreatedEvent(item));
           db.SpaceGroups.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

