//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles CarWashUpdatedEvent: triggered when a car wash is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.CarWashes.EventHandlers;

    public class CarWashUpdatedEventHandler : INotificationHandler<CarWashUpdatedEvent>
    {
        private readonly ILogger<CarWashUpdatedEventHandler> _logger;

        public CarWashUpdatedEventHandler(
            ILogger<CarWashUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CarWashUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
