//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles CarWashCreatedEvent: triggered when a new car wash is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.CarWashes.EventHandlers;

public class CarWashCreatedEventHandler : INotificationHandler<CarWashCreatedEvent>
{
        private readonly ILogger<CarWashCreatedEventHandler> _logger;

        public CarWashCreatedEventHandler(
            ILogger<CarWashCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CarWashCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
