//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles SpaceGroupCreatedEvent: triggered when a new spacegroup is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.EventHandlers;

public class SpaceGroupCreatedEventHandler : INotificationHandler<SpaceGroupCreatedEvent>
{
        private readonly ILogger<SpaceGroupCreatedEventHandler> _logger;

        public SpaceGroupCreatedEventHandler(
            ILogger<SpaceGroupCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(SpaceGroupCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
