//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to retrieve a spacegroup by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same spacegroup.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.SpaceGroups.DTOs;
using CleanArchitecture.Blazor.Application.Features.SpaceGroups.Caching;
using CleanArchitecture.Blazor.Application.Features.SpaceGroups.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Queries.GetById;

public class GetSpaceGroupByIdQuery : ICacheableRequest<Result<SpaceGroupDto>>
{
   public required int Id { get; set; }
   public string CacheKey => SpaceGroupCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => SpaceGroupCacheKey.Tags;
}

public class GetSpaceGroupByIdQueryHandler :
     IRequestHandler<GetSpaceGroupByIdQuery, Result<SpaceGroupDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetSpaceGroupByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<SpaceGroupDto>> Handle(GetSpaceGroupByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.SpaceGroups.ApplySpecification(new SpaceGroupByIdSpecification(request.Id))
                                                .ProjectTo<SpaceGroupDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"SpaceGroup with id: [{request.Id}] not found.");
        return await Result<SpaceGroupDto>.SuccessAsync(data);
    }
}
