//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve all carparks from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Carparks.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Queries.GetAll;

public class GetAllCarparksQuery : ICacheableRequest<IEnumerable<CarparkDto>>
{
   public string CacheKey => CarparkCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => CarparkCacheKey.Tags;
}

public class GetAllCarparksQueryHandler :
     IRequestHandler<GetAllCarparksQuery, IEnumerable<CarparkDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllCarparksQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<CarparkDto>> Handle(GetAllCarparksQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Carparks.ProjectTo<CarparkDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


