//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for AddEditCarparkCommand: enforces field length and required property rules for Carpark entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/carpark
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Carparks.Commands.AddEdit;

public class AddEditCarparkCommandValidator : AbstractValidator<AddEditCarparkCommand>
{
    public AddEditCarparkCommandValidator()
    {
                RuleFor(v => v.AppKey).MaximumLength(255); 
    RuleFor(v => v.MachineCode).MaximumLength(255); 
    RuleFor(v => v.RegistrationCode).MaximumLength(255); 
    RuleFor(v => v.ContactPerson).MaximumLength(255); 
    RuleFor(v => v.PhoneNumber).MaximumLength(255); 
    RuleFor(v => v.Fax).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Identified).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

     }

}

