//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query for retrieving car washes with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CarWashes.DTOs;
using CleanArchitecture.Blazor.Application.Features.CarWashes.Caching;
using CleanArchitecture.Blazor.Application.Features.CarWashes.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Queries.Pagination;

public class CarWashesWithPaginationQuery : CarWashAdvancedFilter, ICacheableRequest<PaginatedData<CarWashDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize},{LicensePlate},{Status},{WashServiceType},{IsPaid}";
    }
    public string CacheKey => CarWashCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => CarWashCacheKey.Tags;
    public CarWashAdvancedSpecification Specification => new CarWashAdvancedSpecification(this);
}
    
public class CarWashesWithPaginationQueryHandler :
         IRequestHandler<CarWashesWithPaginationQuery, PaginatedData<CarWashDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public CarWashesWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<CarWashDto>> Handle(CarWashesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.CarWashes.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<CarWash, CarWashDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}
