//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles MemberDeletedEvent: triggered when a member is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Members.EventHandlers;

    public class MemberDeletedEventHandler : INotificationHandler<MemberDeletedEvent>
    {
        private readonly ILogger<MemberDeletedEventHandler> _logger;

        public MemberDeletedEventHandler(
            ILogger<MemberDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MemberDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
