//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command for adding/editing a zone entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Common;
namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.AddEdit;

public class AddEditZoneCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
    [Description("Name")]
    public required MultiCodeName Name { get; set; }
    [Description("Is main")]
    public bool IsMain {get;set;} 
    [Description("Carpark id")]
    public int CarparkId {get;set;} 
    [Description("Carpark")]
    public CarparkDto? Carpark {get;set;}
    [Description("Holiday sets")]
    public string? HolidaySets { get; set; } = "1,0,0,0,0,0,1,1";
    [Description("Is open cashbox")]
    public bool IsOpenCashbox {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 

    public int Capacity { get; set; } = 100;
    public int Adjustment { get; set; }
    public bool ManualFull { get; set; }
    public int GracePeriod { get; set; } = 15;
    public int ExitBuffer { get; set; } = 15;
    public decimal? LostTicketFee { get; set; } = 300;
    public decimal MonthlyDeposit { get; set; } = 150m;

    public string CacheKey => ZoneCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ZoneDto, AddEditZoneCommand>(MemberList.None);
            CreateMap<AddEditZoneCommand, Zone>(MemberList.None)
                .ForMember(x=>x.Carpark,y=>y.Ignore())
                .ForMember(x=>x.Vehicles,y=>y.Ignore())
                .ForMember(x=>x.Gates,y=>y.Ignore());
        }
    }
}

public class AddEditZoneCommandHandler : IRequestHandler<AddEditZoneCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditZoneCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditZoneCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id > 0)
        {
            var item = await db.Zones.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Zone with id: [{request.Id}] not found.");
            }
            item.CarparkId = request.Carpark!.Id;
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new ZoneUpdatedEvent(item));
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Zone>(request);
            item.CarparkId = request.Carpark!.Id;
            // raise a create domain event
            item.AddDomainEvent(new ZoneCreatedEvent(item));
            db.Zones.Add(item);
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

