//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command for adding/editing a charge entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Charges.Caching;
using CleanArchitecture.Blazor.Application.Features.Charges.DTOs;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.AddEdit;

public class AddEditChargeCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Effective date")]
    public DateTime? EffectiveDate {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Tenant id")]
    public string? TenantId {get;set;} 
    [Description("Tenant")]
    public TenantDto? Tenant {get;set;}
    [Description("Before Content")]
    public RateContent? BeforeContent { get; set; }
    [Description("After Content")]
    public RateContent? AfterContent { get; set; }

    public string CacheKey => ChargeCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ChargeCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ChargeDto, AddEditChargeCommand>(MemberList.None);
            CreateMap<AddEditChargeCommand, Charge>(MemberList.None);
        }
    }
}

public class AddEditChargeCommandHandler : IRequestHandler<AddEditChargeCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditChargeCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditChargeCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id > 0)
        {
            var item = await db.Charges.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Charge with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new ChargeUpdatedEvent(item));
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Charge>(request);
            // raise a create domain event
			item.AddDomainEvent(new ChargeCreatedEvent(item));
            db.Charges.Add(item);
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

