//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles CarWashDeletedEvent: triggered when a car wash is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.CarWashes.EventHandlers;

    public class CarWashDeletedEventHandler : INotificationHandler<CarWashDeletedEvent>
    {
        private readonly ILogger<CarWashDeletedEventHandler> _logger;

        public CarWashDeletedEventHandler(
            ILogger<CarWashDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CarWashDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
