//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for DeleteSpaceGroupCommand: ensures the ID list for spacegroup is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/spacegroup
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Commands.Delete;

public class DeleteSpaceGroupCommandValidator : AbstractValidator<DeleteSpaceGroupCommand>
{
        public DeleteSpaceGroupCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

