//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles CarparkCreatedEvent: triggered when a new carpark is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Carparks.EventHandlers;

public class CarparkCreatedEventHandler : INotificationHandler<CarparkCreatedEvent>
{
        private readonly ILogger<CarparkCreatedEventHandler> _logger;

        public CarparkCreatedEventHandler(
            ILogger<CarparkCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CarparkCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
