//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a member by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same member.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Members.Specifications;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Entities;

namespace CleanArchitecture.Blazor.Application.Features.Members.Queries.GetById;

public class GetMemberByIdQuery : ICacheableRequest<Result<MemberDto>>
{
   public required int Id { get; set; }
   public string CacheKey => MemberCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => MemberCacheKey.Tags;
}

public class GetMemberByIdQueryHandler :
     IRequestHandler<GetMemberByIdQuery, Result<MemberDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetMemberByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<MemberDto>> Handle(GetMemberByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Members.ApplySpecification(new MemberByIdSpecification(request.Id))
                                                .ProjectTo<MemberDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Member with id: [{request.Id}] not found.");

        var memberVehicles = await db.MemberVehicles
                                    .Where(x => x.MemberId == request.Id)
                                    .Select(x => x.Vehicle)
                                    .ProjectTo<VehicleDto>(_mapper.ConfigurationProvider)
                                    .ToListAsync(cancellationToken);
        data.MemberVehicles = memberVehicles;
        var memberRentals = await db.MemberRentals
                                    .Where(x => x.MemberId == request.Id)
                                    .ProjectTo<MemberRentalDto>(_mapper.ConfigurationProvider)
                                    .ToListAsync(cancellationToken);
        data.MemberRentals = memberRentals;
        return await Result<MemberDto>.SuccessAsync(data);
    }
}
