//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles GateDeletedEvent: triggered when a gate is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Gates.EventHandlers;

    public class GateDeletedEventHandler : INotificationHandler<GateDeletedEvent>
    {
        private readonly ILogger<GateDeletedEventHandler> _logger;

        public GateDeletedEventHandler(
            ILogger<GateDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(GateDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
