//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// VehicleDto: transfers vehicle data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Charges.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.DTOs;

[Description("Vehicles")]
public class VehicleDto
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Name")]
    public string Name { get; set; }
    [Description("Service category")]
    public ServiceCategories? ServiceCategoryId { get; set; }
    [Description("Vehicle type")]
    public VehicleTypes? VehicleTypeId { get; set; }
    [Description("Zone id")]
    public int? ZoneId { get; set; }
    [Description("Zone")]
    public ZoneDto? Zone { get; set; }
    [Description("Charge id")]
    public int? ChargeId { get; set; }
    [Description("Charge")]
    public ChargeDto? Charge { get; set; }
    [Description("Capacity")]
    public int Capacity { get; set; }
    [Description("Allow entry when full")]
    public bool AllowEntryWhenFull { get; set; }
    [Description("Manual full")]
    public bool ManualFull { get; set; }
    [Description("Can recognize plate")]
    public bool CanRecognizePlate { get; set; }
    [Description("Is active")]
    public bool IsActive { get; set; }
    [Description("Occupied")]
    public int Occupied { get; set; }
    public int Available => (Capacity - Occupied) < 0 ? 0 : (Capacity - Occupied); //可用泊車位數量

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Vehicle, VehicleDto>(MemberList.None)
                .ForMember(x => x.Zone, y => y.Ignore())
                .ForMember(x => x.Charge, y => y.Ignore());

            CreateMap<VehicleDto, Vehicle>(MemberList.None)
                .ForMember(x => x.Zone, y => y.Ignore())
                .ForMember(x => x.Charge, y => y.Ignore())
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedById, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedAt, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedById, opt => opt.Ignore())
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

