//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to export member data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified member details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Members.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Members.Queries.Export;

public class ExportMembersQuery : MemberAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public MemberAdvancedSpecification Specification => new MemberAdvancedSpecification(this);
      public IEnumerable<string>? Tags => MemberCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => MemberCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportMembersQueryHandler :
         IRequestHandler<ExportMembersQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportMembersQueryHandler> _localizer;
        private readonly MemberDto _dto = new();
        public ExportMembersQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportMembersQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportMembersQuery request, CancellationToken cancellationToken)
        {
            await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
            var data = await db.Members.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<MemberDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<MemberDto, object?>>()
                {
                                     {_localizer[_dto.GetMemberDescription(x=>x.LicensePlate)],item => item.LicensePlate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.CardId)],item => item.CardId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.StartDate)],item => item.StartDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)],item => item.ExpiryDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.SpaceGroupId)],item => item.SpaceGroupId}, 
                    {_localizer[_dto.GetMemberDescription(x=>x.SpaceType)],item => item.SpaceType?.ToString()}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.SpaceNo)],item => item.SpaceNo}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.IsActive)],item => item.IsActive}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)],item => item.PhoneNumber}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.MobileNumber)],item => item.MobileNumber}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Email)],item => item.Email}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Address)],item => item.Address}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Notes)],item => item.Notes}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.TenantId)],item => item.TenantId}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
