//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to retrieve all spacegroups from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.SpaceGroups.DTOs;
using CleanArchitecture.Blazor.Application.Features.SpaceGroups.Caching;

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Queries.GetAll;

public class GetAllSpaceGroupsQuery : ICacheableRequest<IEnumerable<SpaceGroupDto>>
{
   public string CacheKey => SpaceGroupCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => SpaceGroupCacheKey.Tags;
}

public class GetAllSpaceGroupsQueryHandler :
     IRequestHandler<GetAllSpaceGroupsQuery, IEnumerable<SpaceGroupDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllSpaceGroupsQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<SpaceGroupDto>> Handle(GetAllSpaceGroupsQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.SpaceGroups.ProjectTo<SpaceGroupDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


