//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Defines permission constants for holiday operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Holiday Permissions")]
    [Description("Set permissions for holiday operations.")]
    public static class Holidays
    {
        [Description("Allows viewing holiday details.")]
        public const string View = "Permissions.Holidays.View";
        [Description("Allows creating holiday records.")]
        public const string Create = "Permissions.Holidays.Create";
        [Description("Allows cloning existing holiday records.")]
        public const string Clone = "Permissions.Holidays.Clone";
        [Description("Allows modifying existing holiday details.")]
        public const string Edit = "Permissions.Holidays.Edit";
        [Description("Allows deleting holiday records.")]
        public const string Delete = "Permissions.Holidays.Delete";
        [Description("Allows printing holiday details.")]
        public const string Print = "Permissions.Holidays.Print";
        [Description("Allows searching holiday records.")]
        public const string Search = "Permissions.Holidays.Search";
        [Description("Allows exporting holiday records.")]
        public const string Export = "Permissions.Holidays.Export";
        [Description("Allows importing holiday records.")]
        public const string Import = "Permissions.Holidays.Import";
    }
}

public class HolidaysAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Clone { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
