//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a zone by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same zone.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Zones.Queries.GetById;

public class GetZoneByIdQuery : ICacheableRequest<Result<ZoneDto>>
{
   public required int Id { get; set; }
   public string CacheKey => ZoneCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
}

public class GetZoneByIdQueryHandler :
     IRequestHandler<GetZoneByIdQuery, Result<ZoneDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetZoneByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<ZoneDto>> Handle(GetZoneByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Zones.ApplySpecification(new ZoneByIdSpecification(request.Id))
                                                .ProjectTo<ZoneDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Zone with id: [{request.Id}] not found.");
        return await Result<ZoneDto>.SuccessAsync(data);
    }
}
