//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query for retrieving holidays with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Holidays.DTOs;
using CleanArchitecture.Blazor.Application.Features.Holidays.Caching;
using CleanArchitecture.Blazor.Application.Features.Holidays.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Queries.Pagination;

public class HolidaysWithPaginationQuery : HolidayAdvancedFilter, ICacheableRequest<PaginatedData<HolidayDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => HolidayCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => HolidayCacheKey.Tags;
    public HolidayAdvancedSpecification Specification => new HolidayAdvancedSpecification(this);
}
    
public class HolidaysWithPaginationQueryHandler :
         IRequestHandler<HolidaysWithPaginationQuery, PaginatedData<HolidayDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public HolidaysWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<HolidayDto>> Handle(HolidaysWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Holidays.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Holiday, HolidayDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}