//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query for retrieving members with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Members.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.Specifications;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vehicles.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Members.Queries.Pagination;

public class VehiclesPaginationQuery : VehicleAdvancedFilter, ICacheableRequest<PaginatedData<VehicleDto>>
{
    public override string ToString()
    {
        return $"V:{CarparkName}{ZoneName}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => MemberCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => MemberCacheKey.Tags;
    public VehicleAdvancedSpecification Specification => new VehicleAdvancedSpecification(this);
}
    
public class VehiclesPaginationQueryHandler :
         IRequestHandler<VehiclesPaginationQuery, PaginatedData<VehicleDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public VehiclesPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<VehicleDto>> Handle(VehiclesPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Vehicles.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Vehicle, VehicleDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}