//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Import command & template for members.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/member
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Members.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Members.Commands.Import;

    public class ImportMembersCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => MemberCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => MemberCacheKey.Tags;
        public ImportMembersCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateMembersTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportMembersCommandHandler : 
                 IRequestHandler<CreateMembersTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportMembersCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportMembersCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly MemberDto _dto = new();
        private readonly IMapper _mapper;
        public ImportMembersCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportMembersCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportMembersCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, MemberDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.LicensePlate)], (row, item) => item.LicensePlate = row[_localizer[_dto.GetMemberDescription(x=>x.LicensePlate)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.CardId)], (row, item) => item.CardId = row[_localizer[_dto.GetMemberDescription(x=>x.CardId)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.StartDate)], (row, item) => item.StartDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.StartDate)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)], (row, item) => item.ExpiryDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.SpaceGroupId)], (row, item) => item.SpaceGroupId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.SpaceGroupId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.SpaceType)], (row, item) => item.SpaceType = Enum.Parse<SpaceTypes>(row[_localizer[_dto.GetMemberDescription(x=>x.SpaceType)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.SpaceNo)], (row, item) => item.SpaceNo = row[_localizer[_dto.GetMemberDescription(x=>x.SpaceNo)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.IsActive)], (row, item) => item.IsActive =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.IsActive)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x=>x.Name)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)], (row, item) => item.PhoneNumber = row[_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.MobileNumber)], (row, item) => item.MobileNumber = row[_localizer[_dto.GetMemberDescription(x=>x.MobileNumber)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Email)], (row, item) => item.Email = row[_localizer[_dto.GetMemberDescription(x=>x.Email)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Address)], (row, item) => item.Address = row[_localizer[_dto.GetMemberDescription(x=>x.Address)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Notes)], (row, item) => item.Notes = row[_localizer[_dto.GetMemberDescription(x=>x.Notes)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.TenantId)], (row, item) => item.TenantId = row[_localizer[_dto.GetMemberDescription(x=>x.TenantId)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Members.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<Member>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new MemberCreatedEvent(item));
                        await db.Members.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateMembersTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.LicensePlate)], 
_localizer[_dto.GetMemberDescription(x=>x.CardId)], 
_localizer[_dto.GetMemberDescription(x=>x.StartDate)], 
_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)], 
_localizer[_dto.GetMemberDescription(x=>x.SpaceGroupId)], 
_localizer[_dto.GetMemberDescription(x=>x.SpaceNo)], 
_localizer[_dto.GetMemberDescription(x=>x.IsActive)], 
_localizer[_dto.GetMemberDescription(x=>x.Name)], 
_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)], 
_localizer[_dto.GetMemberDescription(x=>x.MobileNumber)], 
_localizer[_dto.GetMemberDescription(x=>x.Email)], 
_localizer[_dto.GetMemberDescription(x=>x.Address)], 
_localizer[_dto.GetMemberDescription(x=>x.Notes)], 
_localizer[_dto.GetMemberDescription(x=>x.TenantId)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

