//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for deleting SpaceGroup entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/spacegroup
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.SpaceGroups.Caching;

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Commands.Delete;

public class DeleteSpaceGroupCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => SpaceGroupCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => SpaceGroupCacheKey.Tags;
  public DeleteSpaceGroupCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteSpaceGroupCommandHandler : 
             IRequestHandler<DeleteSpaceGroupCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteSpaceGroupCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteSpaceGroupCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.SpaceGroups.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new SpaceGroupDeletedEvent(item));
            db.SpaceGroups.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

