//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for AddEditGateCommand: enforces field length and required property rules for Gate entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/gate
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Gates.Commands.AddEdit;

public class AddEditGateCommandValidator : AbstractValidator<AddEditGateCommand>
{
    public AddEditGateCommandValidator()
    {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.GateType).NotNull(); 
    RuleFor(v => v.LaneNo).NotNull(); 
    RuleFor(v => v.HourlyPermitTypes).NotNull(); 
    RuleFor(v => v.MonthlyPermitTypes).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 

     }

}

