//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command for adding/editing a gate entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/gate
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Gates.Caching;
using CleanArchitecture.Blazor.Application.Features.Gates.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Gates.Commands.AddEdit;

public class AddEditGateCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Zone id")]
    public int? ZoneId {get;set;} 
    [Description("Zone")]
    public ZoneDto? Zone {get;set;} 
    [Description("Gate type")]
    public GateType? GateType {get;set;} 
    [Description("Lane no")]
    public int LaneNo {get;set;} 
    [Description("Is upper")]
    public bool IsUpper {get;set;} 
    [Description("Is lefthand")]
    public bool IsLefthand {get;set;}
    [Description("Hourly permit types")]
    public IEnumerable<PermitTypes>? HourlyPermitTypes { get; set; } = [PermitTypes.OctopusCard];
    [Description("Monthly permit types")]
    public IEnumerable<PermitTypes>? MonthlyPermitTypes { get; set; } = [PermitTypes.Smartcard, PermitTypes.LicensePlate];
    [Description("Is active")]
    public bool IsActive {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 


      public string CacheKey => GateCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => GateCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<GateDto, AddEditGateCommand>(MemberList.None);
            CreateMap<AddEditGateCommand, Gate>(MemberList.None);
        }
    }
}

public class AddEditGateCommandHandler : IRequestHandler<AddEditGateCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditGateCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditGateCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id > 0)
        {
            var item = await db.Gates.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Gate with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new GateUpdatedEvent(item));
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Gate>(request);
            // raise a create domain event
			item.AddDomainEvent(new GateCreatedEvent(item));
            db.Gates.Add(item);
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

