//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for deleting Charge entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Charges.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.Delete;

public class DeleteChargeCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => ChargeCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => ChargeCacheKey.Tags;
  public DeleteChargeCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteChargeCommandHandler : 
             IRequestHandler<DeleteChargeCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteChargeCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteChargeCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Charges.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new ChargeDeletedEvent(item));
            db.Charges.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

