//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for deleting Zone entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Zones.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Delete;

public class DeleteZoneCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => ZoneCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
  public DeleteZoneCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteZoneCommandHandler : 
             IRequestHandler<DeleteZoneCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteZoneCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteZoneCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Zones.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new ZoneDeletedEvent(item));
            db.Zones.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

