//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for DeleteZoneCommand: ensures the ID list for zone is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Delete;

public class DeleteZoneCommandValidator : AbstractValidator<DeleteZoneCommand>
{
        public DeleteZoneCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

