//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       Gate entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Gates.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of Gates.
/// </summary>
public class GateAdvancedSpecification : Specification<Gate>
{
    public GateAdvancedSpecification(GateAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(GateListView.TODAY.ToString(), filter.CurrentUser.LocalTimeOffset);
        var last30daysrange = today.GetDateRange(GateListView.LAST_30_DAYS.ToString(),filter.CurrentUser.LocalTimeOffset);

        Query.Where(q => q.Name != null)
              .Where(x=>x.ZoneId==filter.ZoneId,filter.ZoneId!=null)
              .Where(x=>x.Zone.CarparkId==filter.CarparkId,filter.CarparkId!=null)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedById == filter.CurrentUser.UserId, filter.ListView == GateListView.My && filter.CurrentUser is not null)
             .Where(x => x.CreatedAt >= todayrange.Start && x.CreatedAt < todayrange.End.AddDays(1), filter.ListView == GateListView.TODAY)
             .Where(x => x.CreatedAt >= last30daysrange.Start, filter.ListView == GateListView.LAST_30_DAYS);
       
    }
}
