//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for DeleteMemberCommand: ensures the ID list for member is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/member
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Members.Commands.Delete;

public class DeleteMemberCommandValidator : AbstractValidator<DeleteMemberCommand>
{
        public DeleteMemberCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

