//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// UpdateMemberRentalCommand & handler: updates an existing MemberRental with cache invalidation and raises MemberRentalUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.DTOs;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Update;

public class UpdateMemberRentalCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Member id")]
    public int? MemberId {get;set;} 
    [Description("Member")]
    public MemberDto? Member {get;set;} 
    [Description("License plate")]
    public string? LicensePlate {get;set;} 
    [Description("Card id")]
    public string? CardId {get;set;} 
    [Description("Start date")]
    public DateTime? StartDate {get;set;} 
    [Description("Expiry date")]
    public DateTime? ExpiryDate {get;set;} 
    [Description("Rental fee")]
    public decimal RentalFee {get;set;} 
    [Description("Deposit")]
    public decimal Deposit {get;set;} 
    [Description("Amount due")]
    public decimal AmountDue {get;set;} 
    [Description("Amount paid")]
    public decimal AmountPaid {get;set;} 
    [Description("Payment time")]
    public DateTime? PaymentTime {get;set;} 
    [Description("Payment method id")]
    public PaymentMethods? PaymentMethodId {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;} 

      public string CacheKey => MemberRentalCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => new[] { "memberrental", "member" };

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateMemberRentalCommand, MemberRental>(MemberList.None);
            CreateMap<MemberRentalDto,UpdateMemberRentalCommand>(MemberList.None);
        }
    }

}

public class UpdateMemberRentalCommandHandler : IRequestHandler<UpdateMemberRentalCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public UpdateMemberRentalCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }
    public async Task<Result<int>> Handle(UpdateMemberRentalCommand request, CancellationToken cancellationToken)
    {
       await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
       var item = await db.MemberRentals.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"MemberRental with id: [{request.Id}] not found.");
       }
       item = _mapper.Map(request, item);
	    // raise a update domain event
	   item.AddDomainEvent(new MemberRentalUpdatedEvent(item));
       await db.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

