//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for creating a new Zone.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.Caching;
using CleanArchitecture.Blazor.Domain.Common;

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Create;

public class CreateZoneCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
    [Description("Name")]
    public required MultiCodeName Name { get; set; }
    [Description("Is main")]
    public bool IsMain {get;set;} 
    [Description("Carpark id")]
    public int CarparkId {get;set;} 
    [Description("Carpark")]
    public CarparkDto? Carpark {get;set;} 
    [Description("Holiday sets")]
    public string? HolidaySets {get;set;} 
    [Description("Is open cashbox")]
    public bool IsOpenCashbox {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Identifier")]
    public string? Identifier {get;set;} 
    [Description("Holidays")]
    public bool[] Holidays {get;set;} 

      public string CacheKey => ZoneCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateZoneCommand, Zone>(MemberList.None);
        }
    }
}
    
    public class CreateZoneCommandHandler : IRequestHandler<CreateZoneCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateZoneCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateZoneCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<Zone>(request);
           // raise a create domain event
	       item.AddDomainEvent(new ZoneCreatedEvent(item));
           db.Zones.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

