//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Import command & template for memberrentals.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.DTOs;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Import;

    public class ImportMemberRentalsCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => MemberRentalCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => MemberRentalCacheKey.Tags;
        public ImportMemberRentalsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateMemberRentalsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportMemberRentalsCommandHandler : 
                 IRequestHandler<CreateMemberRentalsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportMemberRentalsCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportMemberRentalsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly MemberRentalDto _dto = new();
        private readonly IMapper _mapper;
        public ImportMemberRentalsCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportMemberRentalsCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportMemberRentalsCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, MemberRentalDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.MemberId)], (row, item) => item.MemberId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.MemberId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.LicensePlate)], (row, item) => item.LicensePlate = row[_localizer[_dto.GetMemberDescription(x=>x.LicensePlate)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.CardId)], (row, item) => item.CardId = row[_localizer[_dto.GetMemberDescription(x=>x.CardId)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.StartDate)], (row, item) => item.StartDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.StartDate)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)], (row, item) => item.ExpiryDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.RentalFee)], (row, item) => item.RentalFee =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.RentalFee)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Deposit)], (row, item) => item.Deposit =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.Deposit)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.AmountDue)], (row, item) => item.AmountDue =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.AmountDue)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.AmountPaid)], (row, item) => item.AmountPaid =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.AmountPaid)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.PaymentTime)], (row, item) => item.PaymentTime =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.PaymentTime)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.PaymentMethodId)], (row, item) => item.PaymentMethodId = Enum.Parse<PaymentMethods>(row[_localizer[_dto.GetMemberDescription(x=>x.PaymentMethodId)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Notes)], (row, item) => item.Notes = row[_localizer[_dto.GetMemberDescription(x=>x.Notes)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    
                   
                        var item = _mapper.Map<MemberRental>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new MemberRentalCreatedEvent(item));
                        await db.MemberRentals.AddAsync(item, cancellationToken);
                 
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateMemberRentalsTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.MemberId)], 
_localizer[_dto.GetMemberDescription(x=>x.LicensePlate)], 
_localizer[_dto.GetMemberDescription(x=>x.CardId)], 
_localizer[_dto.GetMemberDescription(x=>x.StartDate)], 
_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)], 
_localizer[_dto.GetMemberDescription(x=>x.RentalFee)], 
_localizer[_dto.GetMemberDescription(x=>x.Deposit)], 
_localizer[_dto.GetMemberDescription(x=>x.AmountDue)], 
_localizer[_dto.GetMemberDescription(x=>x.AmountPaid)], 
_localizer[_dto.GetMemberDescription(x=>x.PaymentTime)], 
_localizer[_dto.GetMemberDescription(x=>x.Notes)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

