//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to export carpark data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified carpark details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Carparks.Caching;
using CleanArchitecture.Blazor.Application.Features.Carparks.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Queries.Export;

public class ExportCarparksQuery : CarparkAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public CarparkAdvancedSpecification Specification => new CarparkAdvancedSpecification(this);
      public IEnumerable<string>? Tags => CarparkCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => CarparkCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportCarparksQueryHandler :
         IRequestHandler<ExportCarparksQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportCarparksQueryHandler> _localizer;
        private readonly CarparkDto _dto = new();
        public ExportCarparksQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportCarparksQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportCarparksQuery request, CancellationToken cancellationToken)
        {
            await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
            var data = await db.Carparks.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<CarparkDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<CarparkDto, object?>>()
                {
                                     {_localizer[_dto.GetMemberDescription(x=>x.AppKey)],item => item.AppKey}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.MachineCode)],item => item.MachineCode}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.RegistrationCode)],item => item.RegistrationCode}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ContactPerson)],item => item.ContactPerson}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.PhoneNumber)],item => item.PhoneNumber}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Fax)],item => item.Fax}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Email)],item => item.Email}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Identified)],item => item.Identified}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.TenantId)],item => item.TenantId}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
