//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles VehicleDeletedEvent: triggered when a vehicle is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Vehicles.EventHandlers;

    public class VehicleDeletedEventHandler : INotificationHandler<VehicleDeletedEvent>
    {
        private readonly ILogger<VehicleDeletedEventHandler> _logger;

        public VehicleDeletedEventHandler(
            ILogger<VehicleDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(VehicleDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
