//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles VehicleUpdatedEvent: triggered when a vehicle is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Vehicles.EventHandlers;

    public class VehicleUpdatedEventHandler : INotificationHandler<VehicleUpdatedEvent>
    {
        private readonly ILogger<VehicleUpdatedEventHandler> _logger;

        public VehicleUpdatedEventHandler(
            ILogger<VehicleUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(VehicleUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
