//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for UpdateHolidayCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a holiday.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Update;

public class UpdateHolidayCommandValidator : AbstractValidator<UpdateHolidayCommand>
{
        public UpdateHolidayCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Date).NotNull(); 
    RuleFor(v => v.Name_En).MaximumLength(255); 
    RuleFor(v => v.Name_Tc).MaximumLength(255); 

          
        }
    
}

