//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for CreateZoneCommand: enforces max lengths and required fields for Zone entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Create;

public class CreateZoneCommandValidator : AbstractValidator<CreateZoneCommand>
{
        public CreateZoneCommandValidator()
        {
                RuleFor(v => v.CarparkId).NotNull(); 
    RuleFor(v => v.HolidaySets).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Identifier).MaximumLength(255); 

        }
       
}

