//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for SpaceGroup-related data. This includes creating unique cache keys for 
//       various spacegroup queries (such as getting all spacegroups, spacegroups by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for SpaceGroup-related data.
/// </summary>
public static class SpaceGroupCacheKey
{
    public const string GetAllCacheKey = "all-SpaceGroups";
    public static string GetPaginationCacheKey(string parameters) {
        return $"SpaceGroupCacheKey:SpaceGroupsWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"SpaceGroupCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"SpaceGroupCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"SpaceGroupCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "spacegroup" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

