//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to export memberrental data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified memberrental details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.DTOs;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Queries.Export;

public class ExportMemberRentalsQuery : MemberRentalAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public MemberRentalAdvancedSpecification Specification => new MemberRentalAdvancedSpecification(this);
      public IEnumerable<string>? Tags => MemberRentalCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => MemberRentalCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportMemberRentalsQueryHandler :
         IRequestHandler<ExportMemberRentalsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportMemberRentalsQueryHandler> _localizer;
        private readonly MemberRentalDto _dto = new();
        public ExportMemberRentalsQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportMemberRentalsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportMemberRentalsQuery request, CancellationToken cancellationToken)
        {
            await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
            var data = await db.MemberRentals.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<MemberRentalDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<MemberRentalDto, object?>>()
                {
                                     {_localizer[_dto.GetMemberDescription(x=>x.MemberId)],item => item.MemberId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.LicensePlate)],item => item.LicensePlate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.CardId)],item => item.CardId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.StartDate)],item => item.StartDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ExpiryDate)],item => item.ExpiryDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.RentalFee)],item => item.RentalFee}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Deposit)],item => item.Deposit}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.AmountDue)],item => item.AmountDue}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.AmountPaid)],item => item.AmountPaid}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.PaymentTime)],item => item.PaymentTime}, 
                    {_localizer[_dto.GetMemberDescription(x=>x.PaymentMethodId)],item => item.PaymentMethodId?.ToString()}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Notes)],item => item.Notes}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
