//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// UpdateCarWashCommand & handler: updates an existing CarWash with cache invalidation and raises CarWashUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/carwash
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CarWashes.DTOs;
using CleanArchitecture.Blazor.Application.Features.CarWashes.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Commands.Update;

public class UpdateCarWashCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("License plate")]
    public string? LicensePlate { get; set; }
    [Description("Vehicle type")]
    public VehicleTypes? VehicleType { get; set; }
    [Description("Wash service type")]
    public WashServiceType? WashServiceType { get; set; }
    [Description("Status")]
    public CarWashStatus? Status { get; set; }
    [Description("Price")]
    public decimal Price { get; set; }
    [Description("Start time")]
    public DateTime? StartTime { get; set; }
    [Description("End time")]
    public DateTime? EndTime { get; set; }
    [Description("Is paid")]
    public bool IsPaid { get; set; }
    [Description("Payment method")]
    public PaymentMethods? PaymentMethod { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }
    [Description("Zone id")]
    public int? ZoneId { get; set; }
    [Description("Zone")]
    public ZoneDto? Zone { get; set; }
    [Description("Tenant id")]
    public string? TenantId { get; set; }
    [Description("Tenant")]
    public TenantDto? Tenant { get; set; }
    public string CacheKey => CarWashCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CarWashCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateCarWashCommand, CarWash>(MemberList.None)
                .ForMember(x => x.Zone, y => y.Ignore())
                .ForMember(x => x.Tenant, y => y.Ignore()); ;
            CreateMap<CarWashDto, UpdateCarWashCommand>(MemberList.None);
        }
    }

}

public class UpdateCarWashCommandHandler : IRequestHandler<UpdateCarWashCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public UpdateCarWashCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }
    public async Task<Result<int>> Handle(UpdateCarWashCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.CarWashes.FindAsync(request.Id, cancellationToken);
        if (item == null)
        {
            return await Result<int>.FailureAsync($"CarWash with id: [{request.Id}] not found.");
        }
        item.ZoneId=request.Zone?.Id;
        item = _mapper.Map(request, item);
        // raise a update domain event
        item.AddDomainEvent(new CarWashUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(item.Id);
    }
}
