//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles ChargeCreatedEvent: triggered when a new charge is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Charges.EventHandlers;

public class ChargeCreatedEventHandler : INotificationHandler<ChargeCreatedEvent>
{
        private readonly ILogger<ChargeCreatedEventHandler> _logger;

        public ChargeCreatedEventHandler(
            ILogger<ChargeCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ChargeCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
