//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles ChargeDeletedEvent: triggered when a charge is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Charges.EventHandlers;

    public class ChargeDeletedEventHandler : INotificationHandler<ChargeDeletedEvent>
    {
        private readonly ILogger<ChargeDeletedEventHandler> _logger;

        public ChargeDeletedEventHandler(
            ILogger<ChargeDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ChargeDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
