//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles ChargeUpdatedEvent: triggered when a charge is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Charges.EventHandlers;

    public class ChargeUpdatedEventHandler : INotificationHandler<ChargeUpdatedEvent>
    {
        private readonly ILogger<ChargeUpdatedEventHandler> _logger;

        public ChargeUpdatedEventHandler(
            ILogger<ChargeUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ChargeUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
