//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve a carpark by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same carpark.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Carparks.Caching;
using CleanArchitecture.Blazor.Application.Features.Carparks.Specifications;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Queries.GetById;

public class GetCarparkByIdQuery : ICacheableRequest<Result<CarparkDto>>
{
   public required int Id { get; set; }
   public string CacheKey => CarparkCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => CarparkCacheKey.Tags;
}

public class GetCarparkByIdQueryHandler :
     IRequestHandler<GetCarparkByIdQuery, Result<CarparkDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetCarparkByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<CarparkDto>> Handle(GetCarparkByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var carpark = await db.Carparks.ApplySpecification(new CarparkByIdSpecification(request.Id))
                                                .ProjectTo<CarparkDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Carpark with id: [{request.Id}] not found.");
        var zones = await db.Zones
                        .Where(z => z.CarparkId == carpark.Id)
                        .OrderBy(z => z.Name.Code)
                        .ProjectTo<ZoneDto>(_mapper.ConfigurationProvider)
                        .ToListAsync(cancellationToken);
        carpark.Zones=zones;
        return await Result<CarparkDto>.SuccessAsync(carpark);
    }
}
