//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a carpark is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class CarparkDeletedEvent : DomainEvent
    {
        public CarparkDeletedEvent(Carpark item)
        {
            Item = item;
        }

        public Carpark Item { get; }
    }

