//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a car wash is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class CarWashDeletedEvent : DomainEvent
    {
        public CarWashDeletedEvent(CarWash item)
        {
            Item = item;
        }

        public CarWash Item { get; }
    }
