//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a gate is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class GateUpdatedEvent : DomainEvent
    {
        public GateUpdatedEvent(Gate item)
        {
            Item = item;
        }

        public Gate Item { get; }
    }

