//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a new holiday is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class HolidayCreatedEvent : DomainEvent
    {
        public HolidayCreatedEvent(Holiday item)
        {
            Item = item;
        }

        public Holiday Item { get; }
    }

