//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a new memberrental is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class MemberRentalCreatedEvent : DomainEvent
    {
        public MemberRentalCreatedEvent(MemberRental item)
        {
            Item = item;
        }

        public MemberRental Item { get; }
    }

