//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a zone is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class ZoneUpdatedEvent : DomainEvent
    {
        public ZoneUpdatedEvent(Zone item)
        {
            Item = item;
        }

        public Zone Item { get; }
    }

