//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for DeleteHolidayCommand: ensures the ID list for holiday is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Delete;

public class DeleteHolidayCommandValidator : AbstractValidator<DeleteHolidayCommand>
{
        public DeleteHolidayCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

