//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for deleting Holiday entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Holidays.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Delete;

public class DeleteHolidayCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => HolidayCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => HolidayCacheKey.Tags;
  public DeleteHolidayCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteHolidayCommandHandler : 
             IRequestHandler<DeleteHolidayCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteHolidayCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteHolidayCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Holidays.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new HolidayDeletedEvent(item));
            db.Holidays.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

