//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to retrieve all gates from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Gates.DTOs;
using CleanArchitecture.Blazor.Application.Features.Gates.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Gates.Queries.GetAll;

public class GetAllGatesQuery : ICacheableRequest<IEnumerable<GateDto>>
{
   public string CacheKey => GateCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => GateCacheKey.Tags;
}

public class GetAllGatesQueryHandler :
     IRequestHandler<GetAllGatesQuery, IEnumerable<GateDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllGatesQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<GateDto>> Handle(GetAllGatesQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Gates.ProjectTo<GateDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


