//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to retrieve all car washes from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CarWashes.DTOs;
using CleanArchitecture.Blazor.Application.Features.CarWashes.Caching;

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Queries.GetAll;

public class GetAllCarWashesQuery : ICacheableRequest<IEnumerable<CarWashDto>>
{
   public string CacheKey => CarWashCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => CarWashCacheKey.Tags;
}

public class GetAllCarWashesQueryHandler :
     IRequestHandler<GetAllCarWashesQuery, IEnumerable<CarWashDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllCarWashesQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<CarWashDto>> Handle(GetAllCarWashesQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.CarWashes.ProjectTo<CarWashDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}
