//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for UpdateGateCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a gate.
// Docs: https://docs.cleanarchitectureblazor.com/features/gate
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Gates.Commands.Update;

public class UpdateGateCommandValidator : AbstractValidator<UpdateGateCommand>
{
        public UpdateGateCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.GateType).NotNull(); 
    RuleFor(v => v.LaneNo).NotNull(); 
    RuleFor(v => v.HourlyPermitTypes).NotNull(); 
    RuleFor(v => v.MonthlyPermitTypes).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 

          
        }
    
}

