//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for DeleteChargeCommand: ensures the ID list for charge is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.Delete;

public class DeleteChargeCommandValidator : AbstractValidator<DeleteChargeCommand>
{
        public DeleteChargeCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

