//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles ZoneUpdatedEvent: triggered when a zone is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Zones.EventHandlers;

    public class ZoneUpdatedEventHandler : INotificationHandler<ZoneUpdatedEvent>
    {
        private readonly ILogger<ZoneUpdatedEventHandler> _logger;

        public ZoneUpdatedEventHandler(
            ILogger<ZoneUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ZoneUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
