//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles ZoneCreatedEvent: triggered when a new zone is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Zones.EventHandlers;

public class ZoneCreatedEventHandler : INotificationHandler<ZoneCreatedEvent>
{
        private readonly ILogger<ZoneCreatedEventHandler> _logger;

        public ZoneCreatedEventHandler(
            ILogger<ZoneCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ZoneCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
