//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for AddEditZoneCommand: enforces field length and required property rules for Zone entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.AddEdit;

public class AddEditZoneCommandValidator : AbstractValidator<AddEditZoneCommand>
{
    public AddEditZoneCommandValidator()
    {
                RuleFor(v => v.CarparkId).NotNull(); 
    RuleFor(v => v.HolidaySets).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 


     }

}

