//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query for retrieving zones with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Zones.Queries.Pagination;

public class ZonesWithPaginationQuery : ZoneAdvancedFilter, ICacheableRequest<PaginatedData<ZoneDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => ZoneCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
    public ZoneAdvancedSpecification Specification => new ZoneAdvancedSpecification(this);
}
    
public class ZonesWithPaginationQueryHandler :
         IRequestHandler<ZonesWithPaginationQuery, PaginatedData<ZoneDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public ZonesWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<ZoneDto>> Handle(ZonesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Zones.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Zone, ZoneDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}