//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for ImportVehiclesCommand: ensures the Data property is non-null and non-empty for vehicle import.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.Import;

public class ImportVehiclesCommandValidator : AbstractValidator<ImportVehiclesCommand>
{
        public ImportVehiclesCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

