//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for creating a new Gate.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/gate
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Gates.Caching;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Gates.Commands.Create;

public class CreateGateCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Zone id")]
    public int? ZoneId {get;set;} 
    [Description("Zone")]
    public ZoneDto? Zone {get;set;} 
    [Description("Gate type")]
    public GateType? GateType {get;set;} 
    [Description("Lane no")]
    public int LaneNo {get;set;} 
    [Description("Is upper")]
    public bool IsUpper {get;set;} 
    [Description("Is lefthand")]
    public bool IsLefthand {get;set;}
    [Description("Hourly permit types")]
    public IEnumerable<PermitTypes>? HourlyPermitTypes { get; set; } = [PermitTypes.OctopusCard];
    [Description("Monthly permit types")]
    public IEnumerable<PermitTypes>? MonthlyPermitTypes { get; set; } = [PermitTypes.Smartcard, PermitTypes.LicensePlate];
    [Description("Is active")]
    public bool IsActive {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 

      public string CacheKey => GateCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => GateCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateGateCommand, Gate>(MemberList.None);
        }
    }
}
    
    public class CreateGateCommandHandler : IRequestHandler<CreateGateCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateGateCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateGateCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<Gate>(request);
           // raise a create domain event
	       item.AddDomainEvent(new GateCreatedEvent(item));
           db.Gates.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

