//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles HolidayDeletedEvent: triggered when a holiday is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Holidays.EventHandlers;

    public class HolidayDeletedEventHandler : INotificationHandler<HolidayDeletedEvent>
    {
        private readonly ILogger<HolidayDeletedEventHandler> _logger;

        public HolidayDeletedEventHandler(
            ILogger<HolidayDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(HolidayDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
