//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Handles HolidayCreatedEvent: triggered when a new holiday is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Holidays.EventHandlers;

public class HolidayCreatedEventHandler : INotificationHandler<HolidayCreatedEvent>
{
        private readonly ILogger<HolidayCreatedEventHandler> _logger;

        public HolidayCreatedEventHandler(
            ILogger<HolidayCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(HolidayCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
