//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// UpdateCarparkCommand & handler: updates an existing Carpark with cache invalidation and raises CarparkUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/carpark
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.Caching;
using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Common;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Commands.Update;

public class UpdateCarparkCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Name")]
    public MultiCodeName Name { get; set; }

    // Car Park Address 停車場地址
    [Description("Address")]
    public MultiName Address { get; set; } = new("", "");

    // Company Name 公司名稱
    [Description("Company Name")]
    public MultiName CompanyName { get; set; } = new("", "");
    [Description("App key")]
    public string? AppKey { get; set; }
    [Description("Machine code")]
    public string? MachineCode { get; set; }
    [Description("Registration code")]
    public string? RegistrationCode { get; set; }
    [Description("Contact person")]
    public string? ContactPerson { get; set; }
    [Description("Phone number")]
    public string? PhoneNumber { get; set; }
    [Description("Fax")]
    public string? Fax { get; set; }
    [Description("Email")]
    public string? Email { get; set; }
    [Description("Description")]
    public string? Description { get; set; }
    [Description("Identified")]
    public string? Identified { get; set; }
    [Description("Tenant id")]
    public string? TenantId { get; set; }
    [Description("Tenant")]
    public TenantDto? Tenant { get; set; }
    [Description("Zones")]
    public List<ZoneDto>? Zones { get; set; } = new List<ZoneDto>();
    public string CacheKey => CarparkCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CarparkCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateCarparkCommand, Carpark>(MemberList.None)
                .ForMember(x => x.Zones, y => y.Ignore())
                .ForMember(x => x.Tenant, y => y.Ignore());
            CreateMap<CarparkDto, UpdateCarparkCommand>(MemberList.None);
        }
    }

}

public class UpdateCarparkCommandHandler : IRequestHandler<UpdateCarparkCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public UpdateCarparkCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }
    public async Task<Result<int>> Handle(UpdateCarparkCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.Carparks.FindAsync(request.Id, cancellationToken);
        if (item == null)
        {
            return await Result<int>.FailureAsync($"Carpark with id: [{request.Id}] not found.");
        }
        item = _mapper.Map(request, item);
        // raise a update domain event
        item.AddDomainEvent(new CarparkUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(item.Id);
    }
}

