//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query for retrieving members with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Members.DTOs;
using CleanArchitecture.Blazor.Application.Features.Members.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.Specifications;
using System.Globalization;

namespace CleanArchitecture.Blazor.Application.Features.Members.Queries.Pagination;

public class MembersWithPaginationQuery : MemberAdvancedFilter, ICacheableRequest<PaginatedData<MemberDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize},{CardId},{LicensePlate},{CarparkId},{Active}";
    }
    public string CacheKey => MemberCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => MemberCacheKey.Tags;
    public MemberAdvancedSpecification Specification => new MemberAdvancedSpecification(this);
}
    
public class MembersWithPaginationQueryHandler :
         IRequestHandler<MembersWithPaginationQuery, PaginatedData<MemberDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public MembersWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<MemberDto>> Handle(MembersWithPaginationQuery request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var data = await db.Members.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Member, MemberDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            await EnrichPaymentStatusAsync(db, data, cancellationToken);
            return data;
        }

        private static async Task EnrichPaymentStatusAsync(
            IApplicationDbContext db,
            PaginatedData<MemberDto> data,
            CancellationToken cancellationToken)
        {
            var members = data.Items.ToList();
            var memberIds = members.Select(x => x.Id).ToArray();
            if (memberIds.Length == 0)
                return;

            var payments = await db.MemberRentals
                .AsNoTracking()
                .Where(x => x.MemberId.HasValue && memberIds.Contains(x.MemberId.Value))
                .Select(x => new
                {
                    MemberId = x.MemberId!.Value,
                    x.StartDate,
                    x.ExpiryDate,
                    x.AmountPaid
                })
                .ToListAsync(cancellationToken);

            var culture = CultureInfo.GetCultureInfo("es-CO");
            var currentMonth = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1);
            var nextMonth = currentMonth.AddMonths(1);

            foreach (var member in members)
            {
                var memberPayments = payments
                    .Where(x => x.MemberId == member.Id && x.AmountPaid > 0)
                    .ToList();

                var currentMonthPaid = memberPayments.Any(x =>
                    (x.StartDate ?? DateTime.MinValue) < nextMonth &&
                    (x.ExpiryDate ?? x.StartDate ?? DateTime.MinValue) >= currentMonth);

                var lastCovered = memberPayments
                    .Select(x => x.ExpiryDate ?? x.StartDate)
                    .Where(x => x.HasValue)
                    .Select(x => x!.Value)
                    .DefaultIfEmpty()
                    .Max();

                if (currentMonthPaid)
                {
                    member.PaymentStatus = "Al dia";
                    member.MonthsOverdue = 0;
                    member.PaidThrough = lastCovered == default ? null : lastCovered;
                }
                else
                {
                    var referenceDate = lastCovered == default ? member.StartDate : lastCovered;
                    var coveredMonth = referenceDate.HasValue
                        ? new DateTime(referenceDate.Value.Year, referenceDate.Value.Month, 1)
                        : currentMonth.AddMonths(-1);
                    var monthsOverdue = Math.Max(1, ((currentMonth.Year - coveredMonth.Year) * 12) + currentMonth.Month - coveredMonth.Month);

                    member.MonthsOverdue = monthsOverdue;
                    member.PaidThrough = lastCovered == default ? null : lastCovered;
                    member.PaymentStatus = monthsOverdue == 1
                        ? "Debe mes actual"
                        : $"Debe {monthsOverdue} meses anteriores";
                }

                if (member.PaidThrough.HasValue)
                {
                    member.LastPaidMonth = culture.TextInfo.ToTitleCase(
                        member.PaidThrough.Value.ToString("MMMM yyyy", culture));
                }
            }

            data.Items = members;
        }
}
