//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for AddEditVehicleCommand: enforces field length and required property rules for Vehicle entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.AddEdit;

public class AddEditVehicleCommandValidator : AbstractValidator<AddEditVehicleCommand>
{
    public AddEditVehicleCommandValidator()
    {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.VehicleTypeId).NotNull(); 
    RuleFor(v => v.Capacity).NotNull(); 
    RuleFor(v => v.Occupied).NotNull(); 

     }

}

