//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a charge is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ChargeDeletedEvent : DomainEvent
    {
        public ChargeDeletedEvent(Charge item)
        {
            Item = item;
        }

        public Charge Item { get; }
    }

