//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a new member is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class MemberCreatedEvent : DomainEvent
    {
        public MemberCreatedEvent(Member item)
        {
            Item = item;
        }

        public Member Item { get; }
    }

