//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a memberrental is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class MemberRentalUpdatedEvent : DomainEvent
    {
        public MemberRentalUpdatedEvent(MemberRental item)
        {
            Item = item;
        }

        public MemberRental Item { get; }
    }

