//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a new spacegroup is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class SpaceGroupCreatedEvent : DomainEvent
    {
        public SpaceGroupCreatedEvent(SpaceGroup item)
        {
            Item = item;
        }

        public SpaceGroup Item { get; }
    }

