//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a new vehicle is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class VehicleCreatedEvent : DomainEvent
    {
        public VehicleCreatedEvent(Vehicle item)
        {
            Item = item;
        }

        public Vehicle Item { get; }
    }

