//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a new zone is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ZoneCreatedEvent : DomainEvent
    {
        public ZoneCreatedEvent(Zone item)
        {
            Item = item;
        }

        public Zone Item { get; }
    }

