//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a specification for filtering a Zone entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Zones.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering Zones by their ID.
/// </summary>
public class ZoneByIdSpecification : Specification<Zone>
{
    public ZoneByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}