//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Import command & template for vehicles.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vehicles.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vehicles.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.Import;

    public class ImportVehiclesCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => VehicleCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => VehicleCacheKey.Tags;
        public ImportVehiclesCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateVehiclesTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportVehiclesCommandHandler : 
                 IRequestHandler<CreateVehiclesTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportVehiclesCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportVehiclesCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly VehicleDto _dto = new();
        private readonly IMapper _mapper;
        public ImportVehiclesCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportVehiclesCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportVehiclesCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, VehicleDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x=>x.Name)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ServiceCategoryId)], (row, item) => item.ServiceCategoryId = Enum.Parse<ServiceCategories>(row[_localizer[_dto.GetMemberDescription(x=>x.ServiceCategoryId)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.VehicleTypeId)], (row, item) => item.VehicleTypeId = Enum.Parse<VehicleTypes>(row[_localizer[_dto.GetMemberDescription(x=>x.VehicleTypeId)]].ToString()) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ZoneId)], (row, item) => item.ZoneId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ZoneId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ChargeId)], (row, item) => item.ChargeId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ChargeId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Capacity)], (row, item) => item.Capacity =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.Capacity)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.AllowEntryWhenFull)], (row, item) => item.AllowEntryWhenFull =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.AllowEntryWhenFull)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.ManualFull)], (row, item) => item.ManualFull =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.ManualFull)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.CanRecognizePlate)], (row, item) => item.CanRecognizePlate =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.CanRecognizePlate)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.IsActive)], (row, item) => item.IsActive =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.IsActive)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Occupied)], (row, item) => item.Occupied =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.Occupied)]]) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Vehicles.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<Vehicle>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new VehicleCreatedEvent(item));
                        await db.Vehicles.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateVehiclesTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.Name)], 
_localizer[_dto.GetMemberDescription(x=>x.ZoneId)], 
_localizer[_dto.GetMemberDescription(x=>x.ChargeId)], 
_localizer[_dto.GetMemberDescription(x=>x.Capacity)], 
_localizer[_dto.GetMemberDescription(x=>x.AllowEntryWhenFull)], 
_localizer[_dto.GetMemberDescription(x=>x.ManualFull)], 
_localizer[_dto.GetMemberDescription(x=>x.CanRecognizePlate)], 
_localizer[_dto.GetMemberDescription(x=>x.IsActive)], 
_localizer[_dto.GetMemberDescription(x=>x.Occupied)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

