//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for UpdateVehicleCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a vehicle.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.Update;

public class UpdateVehicleCommandValidator : AbstractValidator<UpdateVehicleCommand>
{
        public UpdateVehicleCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.VehicleTypeId).NotNull(); 
    RuleFor(v => v.Capacity).NotNull(); 
    RuleFor(v => v.Occupied).NotNull(); 

          
        }
    
}

