//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for creating a new MemberRental.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;
using CleanArchitecture.Blazor.Application.Features.Members.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Create;

public class CreateMemberRentalCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Member id")]
    public int? MemberId {get;set;} 
    [Description("Member")]
    public MemberDto? Member {get;set;} 
    [Description("License plate")]
    public string? LicensePlate {get;set;} 
    [Description("Card id")]
    public string? CardId {get;set;} 
    [Description("Start date")]
    public DateTime? StartDate {get;set;} 
    [Description("Expiry date")]
    public DateTime? ExpiryDate {get;set;} 
    [Description("Rental fee")]
    public decimal RentalFee {get;set;} 
    [Description("Deposit")]
    public decimal Deposit {get;set;} 
    [Description("Amount due")]
    public decimal AmountDue {get;set;} 
    [Description("Amount paid")]
    public decimal AmountPaid {get;set;} 
    [Description("Payment time")]
    public DateTime? PaymentTime {get;set;} 
    [Description("Payment method id")]
    public PaymentMethods? PaymentMethodId {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;} 

      public string CacheKey => MemberRentalCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => new[] { "memberrental", "member" };
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateMemberRentalCommand, MemberRental>(MemberList.None);
        }
    }
}
    
    public class CreateMemberRentalCommandHandler : IRequestHandler<CreateMemberRentalCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateMemberRentalCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateMemberRentalCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<MemberRental>(request);
           // raise a create domain event
	       item.AddDomainEvent(new MemberRentalCreatedEvent(item));
           db.MemberRentals.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

