FROM mcr.microsoft.com/dotnet/aspnet:9.0
RUN echo "deb http://deb.debian.org/debian/ bookworm main contrib" > /etc/apt/sources.list && echo "deb-src http://deb.debian.org/debian/ bookworm main contrib" >> /etc/apt/sources.list && echo "deb http://security.debian.org/ bookworm-security main contrib" >> /etc/apt/sources.list && echo "deb-src http://security.debian.org/ bookworm-security main contrib" >> /etc/apt/sources.list
RUN sed -i'.bak' 's/$/ contrib/' /etc/apt/sources.list
RUN apt-get update && apt-get install -y ttf-mscorefonts-installer fontconfig fonts-noto-cjk openssl && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /app/https && openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout /app/https/private.key -out /app/https/certificate.crt -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost" && openssl pkcs12 -export -out /app/https/aspnetapp.pfx -inkey /app/https/private.key -in /app/https/certificate.crt -password pass:CREDENTIAL_PLACEHOLDER
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_Kestrel__Certificates__Default__Password=CREDENTIAL_PLACEHOLDER
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
WORKDIR /app
EXPOSE 80
COPY publish-blazor/ .
ENTRYPOINT ["dotnet", "CleanArchitecture.Blazor.Server.UI.dll"]
