//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// CarparkDto: transfers carpark data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/carpark
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Common;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;

[Description("Carparks")]
public class CarparkDto
{
    [Description("Id")]
    public int Id { get; set;  }
    // Car Park Name 停車場名稱
    [Description("Name")]
    public MultiCodeName Name { get; set; } = new MultiCodeName("", "", "");

    // Car Park Address 停車場地址
    [Description("Address")]
    public MultiName Address { get; set; } = new("", "");

    // Company Name 公司名稱
    [Description("Company Name")]
    public MultiName CompanyName { get; set; } = new("", "");

    [Description("App key")]
    public string? AppKey {get;set;} 
    [Description("Machine code")]
    public string? MachineCode {get;set;} 
    [Description("Registration code")]
    public string? RegistrationCode {get;set;} 
    [Description("Contact person")]
    public string? ContactPerson {get;set;} 
    [Description("Phone number")]
    public string? PhoneNumber {get;set;} 
    [Description("Fax")]
    public string? Fax {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Zones")]
    public List<ZoneDto>? Zones {get;set;} 
    [Description("Identified")]
    public string? Identified {get;set;} 
    [Description("Tenant id")]
    public string? TenantId {get;set;} 
    [Description("Tenant")]
    public TenantDto? Tenant {get;set;} 


    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Carpark, CarparkDto>(MemberList.None)
                .ForMember(x=>x.Zones,y=>y.Ignore());
            CreateMap<CarparkDto, Carpark>(MemberList.None)
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedById, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedAt, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedById, opt => opt.Ignore())
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

