//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for ImportChargesCommand: ensures the Data property is non-null and non-empty for charge import.
// Docs: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.Import;

public class ImportChargesCommandValidator : AbstractValidator<ImportChargesCommand>
{
        public ImportChargesCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

