//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a new gate is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class GateCreatedEvent : DomainEvent
    {
        public GateCreatedEvent(Gate item)
        {
            Item = item;
        }

        public Gate Item { get; }
    }

