//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a holiday is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class HolidayDeletedEvent : DomainEvent
    {
        public HolidayDeletedEvent(Holiday item)
        {
            Item = item;
        }

        public Holiday Item { get; }
    }

