//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a member is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class MemberUpdatedEvent : DomainEvent
    {
        public MemberUpdatedEvent(Member item)
        {
            Item = item;
        }

        public Member Item { get; }
    }

