//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Domain event for when a member is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class MemberDeletedEvent : DomainEvent
    {
        public MemberDeletedEvent(Member item)
        {
            Item = item;
        }

        public Member Item { get; }
    }

