//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Domain event for when a memberrental is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class MemberRentalDeletedEvent : DomainEvent
    {
        public MemberRentalDeletedEvent(MemberRental item)
        {
            Item = item;
        }

        public MemberRental Item { get; }
    }

