//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for deleting MemberRental entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Delete;

public class DeleteMemberRentalCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => MemberRentalCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => MemberRentalCacheKey.Tags;
  public DeleteMemberRentalCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteMemberRentalCommandHandler : 
             IRequestHandler<DeleteMemberRentalCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteMemberRentalCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteMemberRentalCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.MemberRentals.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new MemberRentalDeletedEvent(item));
            db.MemberRentals.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

