//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for creating a new Carpark.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/carpark
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Carparks.Caching;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Domain.Common;

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Commands.Create;

public class CreateCarparkCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
    [Description("Name")]
    public MultiCodeName Name { get; set; }=new MultiCodeName("", "", "");

    // Car Park Address 停車場地址
    [Description("Address")]
    public MultiName Address { get; set; } = new("", "");

    // Company Name 公司名稱
    [Description("Company Name")]
    public MultiName CompanyName { get; set; } = new("", "");
    [Description("App key")]
    public string? AppKey {get;set;} 
    [Description("Machine code")]
    public string? MachineCode {get;set;} 
    [Description("Registration code")]
    public string? RegistrationCode {get;set;} 
    [Description("Contact person")]
    public string? ContactPerson {get;set;} 
    [Description("Phone number")]
    public string? PhoneNumber {get;set;} 
    [Description("Fax")]
    public string? Fax {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Identified")]
    public string? Identified {get;set;} 
    [Description("Tenant id")]
    public string? TenantId {get;set;} 
    [Description("Tenant")]
    public TenantDto? Tenant {get;set;}
    [Description("Zones")]
    public List<ZoneDto>? Zones { get; set; }=new List<ZoneDto>();
    public string CacheKey => CarparkCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => CarparkCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateCarparkCommand, Carpark>(MemberList.None);
        }
    }
}
    
    public class CreateCarparkCommandHandler : IRequestHandler<CreateCarparkCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateCarparkCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateCarparkCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<Carpark>(request);
           // raise a create domain event
	       item.AddDomainEvent(new CarparkCreatedEvent(item));
           db.Carparks.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

