//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for CreateMemberRentalCommand: enforces max lengths and required fields for MemberRental entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Create;

public class CreateMemberRentalCommandValidator : AbstractValidator<CreateMemberRentalCommand>
{
        public CreateMemberRentalCommandValidator()
        {
                RuleFor(v => v.LicensePlate).MaximumLength(255); 
    RuleFor(v => v.CardId).MaximumLength(255); 
    RuleFor(v => v.RentalFee).NotNull(); 
    RuleFor(v => v.Deposit).NotNull(); 
    RuleFor(v => v.AmountDue).NotNull(); 
    RuleFor(v => v.AmountPaid).NotNull(); 
    RuleFor(v => v.PaymentTime).NotNull(); 
    RuleFor(v => v.PaymentMethodId).NotNull(); 
    RuleFor(v => v.Notes).MaximumLength(255); 

        }
       
}

