//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for ImportMemberRentalsCommand: ensures the Data property is non-null and non-empty for memberrental import.
// Docs: https://docs.cleanarchitectureblazor.com/features/memberrental
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Commands.Import;

public class ImportMemberRentalsCommandValidator : AbstractValidator<ImportMemberRentalsCommand>
{
        public ImportMemberRentalsCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

