//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines a query to export charge data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified charge details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Charges.DTOs;
using CleanArchitecture.Blazor.Application.Features.Charges.Caching;
using CleanArchitecture.Blazor.Application.Features.Charges.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Charges.Queries.Export;

public class ExportChargesQuery : ChargeAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public ChargeAdvancedSpecification Specification => new ChargeAdvancedSpecification(this);
      public IEnumerable<string>? Tags => ChargeCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => ChargeCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportChargesQueryHandler :
         IRequestHandler<ExportChargesQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportChargesQueryHandler> _localizer;
        private readonly ChargeDto _dto = new();
        public ExportChargesQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportChargesQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportChargesQuery request, CancellationToken cancellationToken)
        {
            await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
            var data = await db.Charges.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<ChargeDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<ChargeDto, object?>>()
                {
                                     {_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.EffectiveDate)],item => item.EffectiveDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.TenantId)],item => item.TenantId}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
