//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command and handler for deleting Gate entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/gate
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Gates.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Gates.Commands.Delete;

public class DeleteGateCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => GateCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => GateCacheKey.Tags;
  public DeleteGateCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteGateCommandHandler : 
             IRequestHandler<DeleteGateCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteGateCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteGateCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Gates.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new GateDeletedEvent(item));
            db.Gates.Remove(item);
        }
        await db.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

