//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for ImportHolidaysCommand: ensures the Data property is non-null and non-empty for holiday import.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Import;

public class ImportHolidaysCommandValidator : AbstractValidator<ImportHolidaysCommand>
{
        public ImportHolidaysCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

