//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to retrieve a gate by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same gate.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Gates.DTOs;
using CleanArchitecture.Blazor.Application.Features.Gates.Caching;
using CleanArchitecture.Blazor.Application.Features.Gates.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Gates.Queries.GetById;

public class GetGateByIdQuery : ICacheableRequest<Result<GateDto>>
{
   public required int Id { get; set; }
   public string CacheKey => GateCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => GateCacheKey.Tags;
}

public class GetGateByIdQueryHandler :
     IRequestHandler<GetGateByIdQuery, Result<GateDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetGateByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<GateDto>> Handle(GetGateByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.Gates.ApplySpecification(new GateByIdSpecification(request.Id))
                                                .ProjectTo<GateDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Gate with id: [{request.Id}] not found.");
        return await Result<GateDto>.SuccessAsync(data);
    }
}
