//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for Member-related data. This includes creating unique cache keys for 
//       various member queries (such as getting all members, members by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Members.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for Member-related data.
/// </summary>
public static class MemberCacheKey
{
    public const string GetAllCacheKey = "all-Members";
    public static string GetPaginationCacheKey(string parameters) {
        return $"MemberCacheKey:MembersWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"MemberCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"MemberCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"MemberCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "member" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

