//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for CreateSpaceGroupCommand: enforces max lengths and required fields for SpaceGroup entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/spacegroup
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Commands.Create;

public class CreateSpaceGroupCommandValidator : AbstractValidator<CreateSpaceGroupCommand>
{
        public CreateSpaceGroupCommandValidator()
        {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Capacity).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 

        }
       
}

