//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Validator for CreateChargeCommand: enforces max lengths and required fields for Charge entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/charge
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Charges.Commands.Create;

public class CreateChargeCommandValidator : AbstractValidator<CreateChargeCommand>
{
        public CreateChargeCommandValidator()
        {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.EffectiveDate).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

        }
       
}

