//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for UpdateSpaceGroupCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a spacegroup.
// Docs: https://docs.cleanarchitectureblazor.com/features/spacegroup
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.SpaceGroups.Commands.Update;

public class UpdateSpaceGroupCommandValidator : AbstractValidator<UpdateSpaceGroupCommand>
{
        public UpdateSpaceGroupCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Capacity).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 

          
        }
    
}

