//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for creating a new CarWash.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/carwash
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CarWashes.Caching;
using CleanArchitecture.Blazor.Application.Features.CarWashes.DTOs;
using CleanArchitecture.Blazor.Application.Features.Tenants.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.CarWashes.Commands.Create;

public class CreateCarWashCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("License plate")]
    public string? LicensePlate { get; set; }
    [Description("Vehicle type")]
    public VehicleTypes? VehicleType { get; set; }
    [Description("Wash service type")]
    public WashServiceType? WashServiceType { get; set; }
    [Description("Status")]
    public CarWashStatus? Status { get; set; }
    [Description("Price")]
    public decimal Price { get; set; }
    [Description("Start time")]
    public DateTime? StartTime { get; set; }
    [Description("End time")]
    public DateTime? EndTime { get; set; }
    [Description("Is paid")]
    public bool IsPaid { get; set; }
    [Description("Payment method")]
    public PaymentMethods? PaymentMethod { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }
    [Description("Zone id")]
    public int? ZoneId { get; set; }
    [Description("Zone")]
    public ZoneDto? Zone { get; set; }
    [Description("Tenant id")]
    public string? TenantId { get; set; }
    [Description("Tenant")]
    public TenantDto? Tenant { get; set; }
    public string CacheKey => CarWashCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CarWashCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateCarWashCommand, CarWash>(MemberList.None)
                .ForMember(x => x.Zone, y => y.Ignore())
                .ForMember(x => x.Tenant, y => y.Ignore());
        }
    }
}

public class CreateCarWashCommandHandler : IRequestHandler<CreateCarWashCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public CreateCarWashCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(CreateCarWashCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<CarWash>(request);
        item.StartTime = DateTime.Now;
        item.Status = CarWashStatus.Pending;
        item.IsPaid = false;
        item.ZoneId = request.Zone?.Id;
        // raise a create domain event
        item.AddDomainEvent(new CarWashCreatedEvent(item));
        db.CarWashes.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(item.Id);
    }
}
