//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// ZoneDto: transfers zone data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Carparks.DTOs;
using CleanArchitecture.Blazor.Domain.Common;

namespace CleanArchitecture.Blazor.Application.Features.Zones.DTOs;

[Description("Zones")]
public class ZoneDto
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Name")]
    public required MultiCodeName Name { get; set; }
    [Description("Is main")]
    public bool IsMain {get;set;} 
    [Description("Carpark id")]
    public int CarparkId {get;set;} 
    [Description("Carpark")]
    public CarparkDto? Carpark {get;set;} 
    [Description("Holiday sets")]
    public string? HolidaySets {get;set;} 
    [Description("Is open cashbox")]
    public bool IsOpenCashbox {get;set;} 
    [Description("Vehicles")]
    public List<VehicleDto>? Vehicles {get;set;} 
    [Description("Space groups")]
    public List<SpaceGroupDto>? SpaceGroups {get;set;} 
    [Description("Gates")]
    public List<GateDto>? Gates {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Identifier")]
    public string? Identifier => $"Z{Id}";
    [Description("Holidays")]
    public bool[] Holidays => [.. HolidaySets.Split(',').Select(x => x == "1")];
    

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Zone, ZoneDto>(MemberList.None)
                .ForMember(x=>x.Vehicles,y=>y.Ignore())
                .ForMember(x=>x.SpaceGroups,y=>y.Ignore())
                .ForMember(x=>x.Gates,y=>y.Ignore());
            CreateMap<ZoneDto, Zone>(MemberList.None)
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedById, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedAt, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedById, opt => opt.Ignore())
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

