//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Command for adding/editing a vehicle entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Charges.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vehicles.Caching;
using CleanArchitecture.Blazor.Application.Features.Vehicles.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.AddEdit;

public class AddEditVehicleCommand : ICacheInvalidatorRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Name")]
    public string Name { get; set; }
    [Description("Service category")]
    public ServiceCategories? ServiceCategoryId { get; set; }
    [Description("Vehicle type")]
    public VehicleTypes? VehicleTypeId { get; set; }
    [Description("Zone id")]
    public int? ZoneId { get; set; }
    [Description("Zone")]
    public ZoneDto? Zone { get; set; }
    [Description("Charge id")]
    public int? ChargeId { get; set; }
    [Description("Charge")]
    public ChargeDto? Charge { get; set; }
    [Description("Capacity")]
    public int Capacity { get; set; }
    [Description("Allow entry when full")]
    public bool AllowEntryWhenFull { get; set; }
    [Description("Manual full")]
    public bool ManualFull { get; set; }
    [Description("Can recognize plate")]
    public bool CanRecognizePlate { get; set; }
    [Description("Is active")]
    public bool IsActive { get; set; }
    [Description("Occupied")]
    public int Occupied { get; set; }


    public string CacheKey => VehicleCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => VehicleCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<VehicleDto, AddEditVehicleCommand>(MemberList.None);
            CreateMap<AddEditVehicleCommand, Vehicle>(MemberList.None)
                .ForMember(x=>x.Zone,y=>y.Ignore())
                .ForMember(x=>x.Charge,y=>y.Ignore());
        }
    }
}

public class AddEditVehicleCommandHandler : IRequestHandler<AddEditVehicleCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditVehicleCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditVehicleCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id > 0)
        {
            var item = await db.Vehicles.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Vehicle with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
            item.ChargeId = request.Charge?.Id;
            item.ZoneId = request.Zone?.Id;
            // raise a update domain event
            item.AddDomainEvent(new VehicleUpdatedEvent(item));
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Vehicle>(request);
            item.ChargeId = request.Charge?.Id;
            item.ZoneId = request.Zone?.Id;
            // raise a create domain event
            item.AddDomainEvent(new VehicleCreatedEvent(item));
            db.Vehicles.Add(item);
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }

    }
}

