//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Command and handler for creating a new Holiday.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/holiday
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Holidays.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Holidays.Commands.Create;

public class CreateHolidayCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Date")]
    public DateTime? Date {get;set;} 
    [Description("Name _ en")]
    public string? Name_En {get;set;} 
    [Description("Name _ tc")]
    public string? Name_Tc {get;set;} 

      public string CacheKey => HolidayCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => HolidayCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateHolidayCommand, Holiday>(MemberList.None);
        }
    }
}
    
    public class CreateHolidayCommandHandler : IRequestHandler<CreateHolidayCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateHolidayCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateHolidayCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var item = _mapper.Map<Holiday>(request);
           // raise a create domain event
	       item.AddDomainEvent(new HolidayCreatedEvent(item));
           db.Holidays.Add(item);
           await db.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

