//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Handles MemberRentalDeletedEvent: triggered when a memberrental is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.EventHandlers;

    public class MemberRentalDeletedEventHandler : INotificationHandler<MemberRentalDeletedEvent>
    {
        private readonly ILogger<MemberRentalDeletedEventHandler> _logger;

        public MemberRentalDeletedEventHandler(
            ILogger<MemberRentalDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MemberRentalDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
