//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-17
//     Last Modified: 2025-10-17
//     Description: 
//       Defines the available views for filtering carparks and provides advanced 
//       filtering options for carpark lists. This includes pagination and various 
//       filters such as view types and user-specific filters.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Carparks.Specifications;

#nullable disable warnings
/// <summary>
/// Specifies the different views available for the Carpark list.
/// </summary>
public enum CarparkListView
{
    [Description("All")]
    All,
    [Description("My")]
    My,
    [Description("Created Toady")]
    TODAY,
    [Description("Created within the last 30 days")]
    LAST_30_DAYS
}
/// <summary>
/// A class for applying advanced filtering options to Carpark lists.
/// </summary>
public class CarparkAdvancedFilter: PaginationFilter
{
    public CarparkListView ListView { get; set; } = CarparkListView.All;
    public UserProfile? CurrentUser { get; set; }
}