//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-10-24
//     Last Modified: 2025-10-24
//     Description: 
//       Defines a query to retrieve a memberrental by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same memberrental.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.MemberRentals.DTOs;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Caching;
using CleanArchitecture.Blazor.Application.Features.MemberRentals.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.MemberRentals.Queries.GetById;

public class GetMemberRentalByIdQuery : ICacheableRequest<Result<MemberRentalDto>>
{
   public required int Id { get; set; }
   public string CacheKey => MemberRentalCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => MemberRentalCacheKey.Tags;
}

public class GetMemberRentalByIdQueryHandler :
     IRequestHandler<GetMemberRentalByIdQuery, Result<MemberRentalDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetMemberRentalByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<MemberRentalDto>> Handle(GetMemberRentalByIdQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.MemberRentals.ApplySpecification(new MemberRentalByIdSpecification(request.Id))
                                                .ProjectTo<MemberRentalDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"MemberRental with id: [{request.Id}] not found.");
        return await Result<MemberRentalDto>.SuccessAsync(data);
    }
}
