//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-24
// Validator for CreateVehicleCommand: enforces max lengths and required fields for Vehicle entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/vehicle
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vehicles.Commands.Create;

public class CreateVehicleCommandValidator : AbstractValidator<CreateVehicleCommand>
{
        public CreateVehicleCommandValidator()
        {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.VehicleTypeId).NotNull(); 
    RuleFor(v => v.Capacity).NotNull(); 
    RuleFor(v => v.Occupied).NotNull(); 

        }
       
}

