//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Import command & template for zones.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/zone
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Zones.DTOs;
using CleanArchitecture.Blazor.Application.Features.Zones.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Zones.Commands.Import;

    public class ImportZonesCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => ZoneCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => ZoneCacheKey.Tags;
        public ImportZonesCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateZonesTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportZonesCommandHandler : 
                 IRequestHandler<CreateZonesTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportZonesCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportZonesCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly ZoneDto _dto = new() { Name=new Domain.Common.MultiCodeName("","","") };
        private readonly IMapper _mapper;
        public ImportZonesCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportZonesCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportZonesCommand request, CancellationToken cancellationToken)
        {
           await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, ZoneDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.IsMain)], (row, item) => item.IsMain =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.IsMain)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.CarparkId)], (row, item) => item.CarparkId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.CarparkId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.HolidaySets)], (row, item) => item.HolidaySets = row[_localizer[_dto.GetMemberDescription(x=>x.HolidaySets)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.IsOpenCashbox)], (row, item) => item.IsOpenCashbox =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.IsOpenCashbox)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Description)], (row, item) => item.Description = row[_localizer[_dto.GetMemberDescription(x=>x.Description)]].ToString() }, 
          

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await db.Zones.AnyAsync(x => x.Name.Code == dto.Name.Code, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<Zone>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new ZoneCreatedEvent(item));
                        await db.Zones.AddAsync(item, cancellationToken);
                    }
                 }
                 await db.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateZonesTemplateCommand request, CancellationToken cancellationToken)
        {
            var fields = new string[] {
                   _localizer[_dto.GetMemberDescription(x=>x.IsMain)], 
_localizer[_dto.GetMemberDescription(x=>x.CarparkId)], 
_localizer[_dto.GetMemberDescription(x=>x.HolidaySets)], 
_localizer[_dto.GetMemberDescription(x=>x.IsOpenCashbox)], 
_localizer[_dto.GetMemberDescription(x=>x.Description)], 
_localizer[_dto.GetMemberDescription(x=>x.Identifier)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

