//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-10-17
// Defines permission constants for charge operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------



namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Charge Permissions")]
    [Description("Set permissions for charge operations.")]
    public static class Charges
    {
        [Description("Allows viewing charge details.")]
        public const string View = "Permissions.Charges.View";
        [Description("Allows creating charge records.")]
        public const string Create = "Permissions.Charges.Create";
        [Description("Allows cloning existing charge records.")]
        public const string Clone = "Permissions.Charges.Clone";
        [Description("Allows modifying existing charge details.")]
        public const string Edit = "Permissions.Charges.Edit";
        [Description("Allows deleting charge records.")]
        public const string Delete = "Permissions.Charges.Delete";
        [Description("Allows printing charge details.")]
        public const string Print = "Permissions.Charges.Print";
        [Description("Allows searching charge records.")]
        public const string Search = "Permissions.Charges.Search";
        [Description("Allows exporting charge records.")]
        public const string Export = "Permissions.Charges.Export";
        [Description("Allows importing charge records.")]
        public const string Import = "Permissions.Charges.Import";
    }
}

public class ChargesAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Clone { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
